# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5c1ed65f8ed876e130dec4d528803411f3bafc7efe7661846441289b8ab142440e535985534826fe3a95acca2b8df298f5c3537bfc3b68f5911bdad8f726d19

test:
  secret_key_base: 4dbb9579fc503239a9f367b6868c174eea388d6bd2e0d2d4c4d9d30ff162f3220970456f042d1872179e3cbb8e390e76c7559e8e57ea9550681dae4a54575ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
